### ISSUE TITLE
error on a “Predicted hours to work: xxx.xx”  link 

### ISSUE THREAD

**Issue by mhenke** [trac-hacks/evidencetracplugin#6]
I am receiving an error when clicking on the a “Predicted hours to work: xxx.xx”  link. It goes to something like this http://xxxxx/ticket/423/ebs and I get this error screen.

---

Trac detected an internal error:

KeyError: 'ticket'

This is probably a local installation issue.
Found a bug in Trac?

If you think this should work and you can reproduce the problem, you should consider creating a bug report.

Note that the tracmastertickets plugin seems to be involved. Please report this issue to the plugin maintainer.

Before you do that, though, please first try searching for similar issues, as it is quite likely that this problem has been reported before. For questions about installation and configuration of Trac or its plugins, please try the mailing list instead of creating a ticket.

Otherwise, please ==== How to Reproduce ==== While doing a GET operation on `/ticket/423/ebs`, Trac issued an internal error. ''(please provide additional details here)'' Request parameters: {{{ {} }}} User agent: `Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.16) Gecko/20110319 Firefox/3.6.16` ==== System Information ==== || '''`Trac`''' || `0.12.2` || || '''`Trac`''' || `0.12.2` || || '''`Babel`''' || `0.9.6` || || '''`CustomFieldAdmin`''' || `0.2.5` || || '''`Genshi`''' || `0.6` || || '''`GIT`''' || `1.7.3.1.msysgit.0` || || '''`mod_python`''' || `3.3.1` || || '''`pysqlite`''' || `2.5.5` || || '''`Python`''' || `2.5.4 (r254:67916, Dec 23 2008, 15:10:54) [MSC v.1310 32 bit (Intel)]` || || '''`Python`''' || `2.5.4 (r254:67916, Dec 23 2008, 15:10:54) [MSC v.1310 32 bit (Intel)]` || || '''`RPC`''' || `1.1.0-r9395` || || '''`setuptools`''' || `0.6c11` || || '''`setuptools`''' || `0.6c11` || || '''`SQLite`''' || `3.6.11` || || '''`Subversion`''' || `1.6.6 (r40053)` || || '''`jQuery`''' || `1.4.2` || ==== Enabled Plugins ==== || '''`batchmodify`''' || `0.8.0-trac0.12` || || '''`duplicateticketsearch`''' || `1.0.1` || || '''`estimationtools`''' || `0.4.5` || || '''`evidence-scheduling`''' || `0.1.4.2` || || '''`graphviz`''' || `0.7.5` || || '''`gridmodify`''' || `0.1.5` || || '''`roadmaphours`''' || `0.5` || || '''`ticketimport`''' || `0.8` || || '''`timingandestimationplugin`''' || `1.1.2` || || '''`tracaccountmanager`''' || `0.3dev-r9929` || || '''`tracannouncer`''' || `0.11.1` || || '''`traccustomfieldadmin`''' || `0.2.5` || || '''`tracdatefield`''' || `1.0.1` || || '''`tracdynamicfields`''' || `1.2.1` || || '''`tracextracturl`''' || `0.3` || || '''`tracgit`''' || `0.12.0.5dev` || || '''`tracmastertickets`''' || `3.0.2` || || '''`tracmenusplugin`''' || `0.1` || || '''`tracsectioneditplugin`''' || `0.1` || || '''`tracsimpleticket`''' || `2.0` || || '''`tracstats`''' || `0.4` || || '''`tracsumfields`''' || `1.0.1` || || '''`tracticketchangelogplugin`''' || `0.1` || || '''`tracticketdepgraph`''' || `0.11` || || '''`tractocmacro`''' || `11.0.0.3` || || '''`tracxmlrpc`''' || `1.1.0-r9395` || ==== Python Traceback ==== {{{ Traceback (most recent call last): File "c:\docume~1\mhenke\locals~1\temp\1\easy_install-n0xiam\Trac-0.12.2-py2.5-win32.egg.tmp\trac\web\main.py", line 511, in _dispatch_request dispatcher.dispatch(req) File "c:\docume~1\mhenke\locals~1\temp\1\easy_install-n0xiam\Trac-0.12.2-py2.5-win32.egg.tmp\trac\web\main.py", line 248, in dispatch self._post_process_request(req, *resp) File "c:\docume~1\mhenke\locals~1\temp\1\easy_install-n0xiam\Trac-0.12.2-py2.5-win32.egg.tmp\trac\web\main.py", line 357, in _post_process_request resp = f.post_process_request(req, *resp) File "build\bdist.win32\egg\mastertickets\web_ui.py", line 47, in post_process_request tkt = data['ticket'] KeyError: 'ticket' }}} a new bug report describing the problem and explain how to reproduce it.
Python Traceback
Most recent call last:

```
* File "c:/docume~1/mhenke/locals~1/temp/1/easy_install-n0xiam/Trac-0.12.2-py2.5-win32.egg.tmp/trac/web/main.py", line 511, in _dispatch_request
  Code fragment:
  Line  
  506   try:
  507   if not env and env_error:
  508   raise HTTPInternalError(env_error)
  509   try:
  510   dispatcher = RequestDispatcher(env)
  511   dispatcher.dispatch(req)
  512   except RequestDone:
  513   pass
  514   resp = req._response or []
  515    
  516   except HTTPException, e:
  Local variables:
  Name  Value
  dispatcher    <trac.web.main.RequestDispatcher object at 0x032E35B0>
  e     KeyError('ticket',)
  env   <trac.env.Environment object at 0x027F2750>
  env_error     None
  req   <Request "GET '/ticket/423/ebs'">
  resp  []
* File "c:/docume~1/mhenke/locals~1/temp/1/easy_install-n0xiam/Trac-0.12.2-py2.5-win32.egg.tmp/trac/web/main.py", line 248, in dispatch
  Code fragment:
  Line  
  243   # Give the session a chance to persist changes
  244   req.session.save()
  245   req.display(template, content_type or 'text/html')
  246   else: # Genshi
  247   template, data, content_type = \
  248   self._post_process_request(req, *resp)
  249   if 'hdfdump' in req.args:
  250   req.perm.require('TRAC_ADMIN')
  251   # debugging helper - no need to render first
  252   out = StringIO()
  253   pprint(data, out)
  Local variables:
  Name  Value
  chosen_handler    <evidence.ticket_ebs.EvidenceSchedulingTicket object at 0x0310EFD0>
  chrome    <trac.web.chrome.Chrome object at 0x0311F0D0>
  err   (<type 'exceptions.KeyError'>, KeyError('ticket',), <traceback object at ...
  handler   <evidence.ticket_ebs.EvidenceSchedulingTicket object at 0x0310EFD0>
  req   <Request "GET '/ticket/423/ebs'">
  resp  ('evidence.html', {'dateinfo': <function dateinfo at 0x032AA570>, 'owner': ...
  self  <trac.web.main.RequestDispatcher object at 0x032E35B0>
* File "c:/docume~1/mhenke/locals~1/temp/1/easy_install-n0xiam/Trac-0.12.2-py2.5-win32.egg.tmp/trac/web/main.py", line 357, in _post_process_request
  Code fragment:
  Line  
  352   # Trac 0.10, only filters with same arity gets passed real values.
  353   # Errors will call all filters with None arguments,
  354   # and results will not be not saved.
  355   extra_arg_count = arity(f.post_process_request) - 1
  356   if extra_arg_count == nbargs:
  357   resp = f.post_process_request(req, *resp)
  358   elif nbargs == 0:
  359   f.post_process_request(req, *(None,)*extra_arg_count)
  360   return resp
  361    
  362    
  Local variables:
  Name  Value
  args  ('evidence.html', {'dateinfo': <function dateinfo at 0x032AA570>, 'owner': ...
  extra_arg_count   3
  f     <mastertickets.web_ui.MasterTicketsModule object at 0x0310EF70>
  nbargs    3
  req   <Request "GET '/ticket/423/ebs'">
  resp  ('evidence.html', {'dateinfo': <function dateinfo at 0x032AA570>, 'owner': ...
  self  <trac.web.main.RequestDispatcher object at 0x032E35B0>
* File "build/bdist.win32/egg/mastertickets/web_ui.py", line 47, in post_process_request
  Code fragment:
  Line  
  42    def post_process_request(self, req, template, data, content_type):
  43    if req.path_info.startswith('/ticket/'):
  44    # In case of an invalid ticket, the data is invalid
  45    if not data:
  46    return template, data, content_type
  47    tkt = data['ticket']
  48    links = TicketLinks(self.env, tkt)
  49    
  50    for i in links.blocked_by:
  51    if Ticket(self.env, i)['status'] != 'closed':
  52    add_script(req, 'mastertickets/disable_resolve.js')
  Local variables:
  Name  Value
  content_type  None
  data  {'dateinfo': <function dateinfo at 0x032AA570>, 'owner': u'somebody', ...
  req   <Request "GET '/ticket/423/ebs'">
  self  <mastertickets.web_ui.MasterTicketsModule object at 0x0310EF70>
  template  'evidence.html'
```

File "c:/docume~1/mhenke/locals~1/temp/1/easy_install-n0xiam/Trac-0.12.2-py2.5-win32.egg.tmp/trac/web/main.py", line 511, in _dispatch_request
  dispatcher.dispatch(req)
File "c:/docume~1/mhenke/locals~1/temp/1/easy_install-n0xiam/Trac-0.12.2-py2.5-win32.egg.tmp/trac/web/main.py", line 248, in dispatch
  self._post_process_request(req, *resp)
File "c:/docume~1/mhenke/locals~1/temp/1/easy_install-n0xiam/Trac-0.12.2-py2.5-win32.egg.tmp/trac/web/main.py", line 357, in _post_process_request
  resp = f.post_process_request(req, *resp)
File "build/bdist.win32/egg/mastertickets/web_ui.py", line 47, in post_process_request
  tkt = data['ticket']

System Information:

User Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.16) Gecko/20110319 Firefox/3.6.16
Trac    0.12.2
Trac    0.12.2
Babel   0.9.6
CustomFieldAdmin    0.2.5
Genshi  0.6
GIT     1.7.3.1.msysgit.0
mod_python  3.3.1
pysqlite    2.5.5
Python  2.5.4 (r254:67916, Dec 23 2008, 15:10:54) [MSC v.1310 32 bit (Intel)]
Python  2.5.4 (r254:67916, Dec 23 2008, 15:10:54) [MSC v.1310 32 bit (Intel)]
RPC     1.1.0-r9395
setuptools  0.6c11
setuptools  0.6c11
SQLite  3.6.11
Subversion  1.6.6 (r40053)
jQuery  1.4.2

**Comment by lucalenardi** [comment]
Exactly the same problem here.

```
Trac    0.12.2
Genshi  0.6
GIT 1.7.4.1
Mercurial   1.7.5
mod_wsgi    3.3 (WSGIProcessGroup template_project WSGIApplicationGroup %{GLOBAL})
Pygments    1.4
pysqlite    2.6.0
Python  2.7.1+ (r271:86832, Apr 11 2011, 18:37:12) [GCC 4.5.2]
setuptools  0.6
SQLite  3.7.4
Subversion  1.6.12 (r955767)
jQuery  1.4.2
```
